name: CI

on:
  push:  
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt check
        run: |
          forge fmt --check ./back

      - name: Run Forge build
        run: |
          forge build --sizes --names ./back

      - name: Run Forge tests
        run: |
          forge test -vvv ./back
